### ISSUE TITLE
Decoupling SecureADODB code base

### ISSUE THREAD

**Issue by pchemguy** [pchemguy/SecureADODB-Fork#13]
There are a few aspects where decoupling of the SecureADODB code base can be improved.

- [x] Removing _IDbConnection_CreateCommand_ interface (issue https://github.com/pchemguy/RDVBA-examples/issues/14)
- [x] Decoupling _IDbCommandFactory_ <-> _DefaultDbCommand_ (issue https://github.com/pchemguy/RDVBA-examples/issues/6)
- [x] Decoupling _UnitOfWork_ <-> _DefaultDbCommand_ (issue https://github.com/pchemguy/RDVBA-examples/issues/5)

Branch [_SecureADODB/DbCommandFactory_](https://github.com/pchemguy/RDVBA-examples/tree/SecureADODB/DbCommandFactory)
