### ISSUE TITLE
Class design conventions

### ISSUE THREAD

**Issue by pchemguy** [pchemguy/SecureADODB-Fork#9]
Class design conventions:
- [x] Create vs CreateInstance factories (issue https://github.com/pchemguy/RDVBA-examples/issues/10)
- [x] Create and CreInit - factory and constructor (issue https://github.com/pchemguy/RDVBA-examples/issues/11)
- [x] Self and Class properties (issue https://github.com/pchemguy/RDVBA-examples/issues/12)
